require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Produce::FruitsController do

  # This should return the minimal set of attributes required to create a valid
  # Produce::Fruit. As you add validations to Produce::Fruit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      kind: 'apple',
      variety: 'fugi'
    }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Produce::FruitsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all produce_fruits as @produce_fruits" do
      fruit = Produce::Fruit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:produce_fruits).should eq([fruit])
    end
  end

  describe "GET show" do
    it "assigns the requested fruit as @fruit" do
      fruit = Produce::Fruit.create! valid_attributes
      get :show, {:id => fruit.to_param}, valid_session
      assigns(:produce_fruit).should eq(fruit)
    end
  end

  describe "GET new" do
    it "assigns a new fruit as @fruit" do
      get :new, {}, valid_session
      assigns(:produce_fruit).should be_a_new(Produce::Fruit)
    end
  end

  describe "GET edit" do
    it "assigns the requested fruit as @fruit" do
      fruit = Produce::Fruit.create! valid_attributes
      get :edit, {:id => fruit.to_param}, valid_session
      assigns(:produce_fruit).should eq(fruit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Produce::Fruit" do
        expect {
          post :create, {:produce_fruit => valid_attributes}, valid_session
        }.to change(Produce::Fruit, :count).by(1)
      end

      it "assigns a newly created fruit as @fruit" do
        post :create, {:produce_fruit => valid_attributes}, valid_session
        assigns(:produce_fruit).should be_a(Produce::Fruit)
        assigns(:produce_fruit).should be_persisted
      end

      it "redirects to the created fruit" do
        post :create, {:produce_fruit => valid_attributes}, valid_session
        response.should redirect_to(Produce::Fruit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fruit as @fruit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Produce::Fruit.any_instance.stub(:save).and_return(false)
        post :create, {:produce_fruit => {}}, valid_session
        assigns(:produce_fruit).should be_a_new(Produce::Fruit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Produce::Fruit.any_instance.stub(:save).and_return(false)
        post :create, {:produce_fruit => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fruit" do
        fruit = Produce::Fruit.create! valid_attributes
        # Assuming there are no other produce_fruits in the database, this
        # specifies that the Produce::Fruit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Produce::Fruit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => fruit.to_param, :produce_fruit => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested fruit as @fruit" do
        fruit = Produce::Fruit.create! valid_attributes
        put :update, {:id => fruit.to_param, :produce_fruit => valid_attributes}, valid_session
        assigns(:produce_fruit).should eq(fruit)
      end

      it "redirects to the fruit" do
        fruit = Produce::Fruit.create! valid_attributes
        put :update, {:id => fruit.to_param, :produce_fruit => valid_attributes}, valid_session
        response.should redirect_to(fruit)
      end
    end

    describe "with invalid params" do
      it "assigns the fruit as @fruit" do
        fruit = Produce::Fruit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Produce::Fruit.any_instance.stub(:save).and_return(false)
        put :update, {:id => fruit.to_param, :produce_fruit => {}}, valid_session
        assigns(:produce_fruit).should eq(fruit)
      end

      it "re-renders the 'edit' template" do
        fruit = Produce::Fruit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Produce::Fruit.any_instance.stub(:save).and_return(false)
        put :update, {:id => fruit.to_param, :produce_fruit => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fruit" do
      fruit = Produce::Fruit.create! valid_attributes
      expect {
        delete :destroy, {:id => fruit.to_param}, valid_session
      }.to change(Produce::Fruit, :count).by(-1)
    end

    it "redirects to the produce_fruits list" do
      fruit = Produce::Fruit.create! valid_attributes
      delete :destroy, {:id => fruit.to_param}, valid_session
      response.should redirect_to(produce_fruits_url)
    end
  end

end
